### ISSUE TITLE
Bad Host returned when using docker container behind reverse proxy

### ISSUE THREAD

**Issue by minnixtx** [ssbc/go-ssb-room#267]
Unable to reach the web interface, greeted by Bad Host text. Docker running on fresh install of Ubuntu Server 20.04.3 x86-64 machine. My configs:

.env
```
# SPDX-FileCopyrightText: 2021 The NGI Pointer Secure-Scuttlebutt Team of 2020/2021
#
# SPDX-License-Identifier: Unlicense

HTTPS_DOMAIN=https://lugroom.minnix.dev
ALIASES_AS_SUBDOMAINS=false
# uncomment variable  if you want to store data in a custom directory (required for default docker-compose setup)
 REPO=/ssb-go-room-secrets
```

docker-compose.yml
```
# SPDX-FileCopyrightText: 2021 The NGI Pointer Secure-Scuttlebutt Team of 2020/2021
#
# SPDX-License-Identifier: CC0-1.0

version: '3'
services:
  room:
    build: .
    command: 'sh start.sh'
    env_file: .env
    ports:
      -  "3000:3000" # Proxypass this port through NGINX or Apache as your HTTP landing & dashboard page
      - "0.0.0.0:8008:8008" # This is the port SSB clients connect to
    volumes:
      - ./ssb-go-room-secrets:/ssb-go-room-secrets
```

My nginx proxy config running on my proxy server, using certbot to generate cert:
```
server {
    server_name lugroom.minnix.dev;

location / {
        proxy_pass http://192.168.57.226:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $remote_addr:$remote_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        # for websocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }



    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/lugroom.minnix.dev/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/lugroom.minnix.dev/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = lugroom.minnix.dev) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name lugroom.minnix.dev;
    listen 80;
    return 404; # managed by Certbot


}
```

BTW, I cannot reach the web interface via local IP within my network either.
